## Kowshik
## Orden - Over Sampling
## Accuracy - 0.99

In [1]:
import pandas as pd;
import numpy as np;
from matplotlib import pyplot as plt;
import seaborn as sns;

In [2]:
rawData = pd.read_csv("finalOutput_orden.csv")

rawData

,S.No,BP,AT,PM10,RH,PM2.5,WD,WS,NH3,CO,NO,NO2,NOx,SO2,Ozone,AQI Simulink,Label
0,1,739.927841,29.592495,444.669402,50.346059,155.981714,182.398863,1.685305,49.899503,1.667151,94.785703,76.884928,229.145198,23.380207,29.654703,6.285714,Moderate
1,2,739.927841,29.592495,444.669402,50.346059,155.981714,182.398863,1.685305,49.899503,1.667151,94.785703,76.884928,229.145198,23.380207,29.654703,6.285714,Moderate
2,3,739.927841,29.592495,444.669402,50.346059,155.981714,182.398863,1.685305,49.899503,1.667151,94.785703,76.884928,229.145198,23.380207,29.654703,6.285714,Moderate
3,4,739.927841,29.592495,444.669402,50.346059,155.981714,182.398863,1.685305,49.899503,1.667151,94.785703,76.884928,229.145198,23.380207,29.654703,6.285714,Moderate
4,5,739.927841,29.592495,444.669402,50.346059,155.981714,182.398863,1.685305,49.899503,1.667151,94.785703,76.884928,229.145198,23.380207,29.654703,6.285714,Moderate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2491,2492,972.180417,34.841250,112.833333,68.402083,41.104167,91.885417,2.437917,40.789167,1.719583,7.340833,26.114167,19.872500,6.555000,21.977046,4.575486,Moderate
2492,2493,972.026250,36.314167,288.927083,59.525833,75.822917,237.239583,0.865833,29.330000,2.177561,96.387500,44.670833,102.346250,8.974583,7.061667,5.285714,Moderate
2493,2494,971.963750,32.397500,83.135417,84.377083,44.541667,131.479167,0.590000,39.906704,2.177561,86.847517,71.109110,111.700845,10.585417,12.381667,5.285714,Moderate
2494,2495,972.887083,34.719167,312.250000,55.533750,75.531250,248.406250,0.470417,34.950417,2.177561,166.466563,86.191250,187.012119,21.204167,30.482500,5.699442,Moderate
2495,2496,973.959583,24.862500,716.533963,72.664167,264.003210,228.958333,0.300000,52.736534,2.177561,225.919276,158.741667,274.951461,18.738416,5.662917,4.137296,Healthy

In [3]:
rawData.drop(rawData.columns[[0, 15]], axis = 1, inplace = True);

clientDataAltered = rawData;

clientDataAltered

,BP,AT,PM10,RH,PM2.5,WD,WS,NH3,CO,NO,NO2,NOx,SO2,Ozone,Label
0,739.927841,29.592495,444.669402,50.346059,155.981714,182.398863,1.685305,49.899503,1.667151,94.785703,76.884928,229.145198,23.380207,29.654703,Moderate
1,739.927841,29.592495,444.669402,50.346059,155.981714,182.398863,1.685305,49.899503,1.667151,94.785703,76.884928,229.145198,23.380207,29.654703,Moderate
2,739.927841,29.592495,444.669402,50.346059,155.981714,182.398863,1.685305,49.899503,1.667151,94.785703,76.884928,229.145198,23.380207,29.654703,Moderate
3,739.927841,29.592495,444.669402,50.346059,155.981714,182.398863,1.685305,49.899503,1.667151,94.785703,76.884928,229.145198,23.380207,29.654703,Moderate
4,739.927841,29.592495,444.669402,50.346059,155.981714,182.398863,1.685305,49.899503,1.667151,94.785703,76.884928,229.145198,23.380207,29.654703,Moderate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2491,972.180417,34.841250,112.833333,68.402083,41.104167,91.885417,2.437917,40.789167,1.719583,7.340833,26.114167,19.872500,6.555000,21.977046,Moderate
2492,972.026250,36.314167,288.927083,59.525833,75.822917,237.239583,0.865833,29.330000,2.177561,96.387500,44.670833,102.346250,8.974583,7.061667,Moderate
2493,971.963750,32.397500,83.135417,84.377083,44.541667,131.479167,0.590000,39.906704,2.177561,86.847517,71.109110,111.700845,10.585417,12.381667,Moderate
2494,972.887083,34.719167,312.250000,55.533750,75.531250,248.406250,0.470417,34.950417,2.177561,166.466563,86.191250,187.012119,21.204167,30.482500,Moderate
2495,973.959583,24.862500,716.533963,72.664167,264.003210,228.958333,0.300000,52.736534,2.177561,225.919276,158.741667,274.951461,18.738416,5.662917,Healthy

In [4]:

columns = clientDataAltered.columns.tolist()

columns = [c for c in columns if c not in ["Label"]]

target = "Label"

state = np.random.RandomState(42)

x = clientDataAltered[columns]

y = clientDataAltered[target]

In [5]:
x

,BP,AT,PM10,RH,PM2.5,WD,WS,NH3,CO,NO,NO2,NOx,SO2,Ozone
0,739.927841,29.592495,444.669402,50.346059,155.981714,182.398863,1.685305,49.899503,1.667151,94.785703,76.884928,229.145198,23.380207,29.654703
1,739.927841,29.592495,444.669402,50.346059,155.981714,182.398863,1.685305,49.899503,1.667151,94.785703,76.884928,229.145198,23.380207,29.654703
2,739.927841,29.592495,444.669402,50.346059,155.981714,182.398863,1.685305,49.899503,1.667151,94.785703,76.884928,229.145198,23.380207,29.654703
3,739.927841,29.592495,444.669402,50.346059,155.981714,182.398863,1.685305,49.899503,1.667151,94.785703,76.884928,229.145198,23.380207,29.654703
4,739.927841,29.592495,444.669402,50.346059,155.981714,182.398863,1.685305,49.899503,1.667151,94.785703,76.884928,229.145198,23.380207,29.654703
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2491,972.180417,34.841250,112.833333,68.402083,41.104167,91.885417,2.437917,40.789167,1.719583,7.340833,26.114167,19.872500,6.555000,21.977046
2492,972.026250,36.314167,288.927083,59.525833,75.822917,237.239583,0.865833,29.330000,2.177561,96.387500,44.670833,102.346250,8.974583,7.061667
2493,971.963750,32.397500,83.135417,84.377083,44.541667,131.479167,0.590000,39.906704,2.177561,86.847517,71.109110,111.700845,10.585417,12.381667
2494,972.887083,34.719167,312.250000,55.533750,75.531250,248.406250,0.470417,34.950417,2.177561,166.466563,86.191250,187.012119,21.204167,30.482500
2495,973.959583,24.862500,716.533963,72.664167,264.003210,228.958333,0.300000,52.736534,2.177561,225.919276,158.741667,274.951461,18.738416,5.662917

In [6]:
y

0       Moderate
1       Moderate
2       Moderate
3       Moderate
4       Moderate
          ...
2491    Moderate
2492    Moderate
2493    Moderate
2494    Moderate
2495     Healthy
Name: Label, Length: 2496, dtype: object

In [7]:
countClass_moderate, countClass_Healthy, countClass_Unhealthy = clientDataAltered.Label.value_counts()

In [8]:
countClass_moderate, countClass_Healthy, countClass_Unhealthy

(2138, 253, 105)

In [9]:
x.shape, y.shape

((2496, 14), (2496,))

In [10]:

Moderate = clientDataAltered[clientDataAltered["Label"] == "Moderate"]

Healthy = clientDataAltered[clientDataAltered["Label"] == "Healthy"]

Unhealthy = clientDataAltered[clientDataAltered["Label"] == "Unhealthy"]

In [11]:
Moderate.shape, Healthy.shape, Unhealthy.shape

((2138, 15), (105, 15), (253, 15))

In [12]:

from imblearn.over_sampling import SMOTE

overSample = SMOTE(random_state = 42)

x_res, y_res = overSample.fit_resample(x, y)

In [13]:
x_res.shape, y_res.shape

((6414, 14), (6414,))

In [14]:
from collections import Counter

print("Original dataset shape {}".format(Counter(y)))

print("Resampled dataset shape {}".format(Counter(y_res)))

Original dataset shape Counter({'Moderate': 2138, 'Unhealthy': 253, 'Healthy': 105})
Resampled dataset shape Counter({'Moderate': 2138, 'Healthy': 2138, 'Unhealthy': 2138})

In [15]:
from imblearn.over_sampling import RandomOverSampler

os = RandomOverSampler(random_state = 42, sampling_strategy='auto')


x_train_res, y_train_res = os.fit_resample(x, y)

In [16]:
x_train_res.shape, y_train_res.shape

((6414, 14), (6414,))

In [17]:
from collections import Counter

print("Original dataset shape {}".format(Counter(y)))

print("Resampled dataset shape {}".format(Counter(y_train_res)))

Original dataset shape Counter({'Moderate': 2138, 'Unhealthy': 253, 'Healthy': 105})
Resampled dataset shape Counter({'Moderate': 2138, 'Healthy': 2138, 'Unhealthy': 2138})

In [18]:

from sklearn.model_selection import train_test_split;

x_train, x_test, y_train, y_test = train_test_split(x_train_res, y_train_res, test_size = 1/3, random_state = 6, stratify = y_train_res);

In [19]:
x_test.shape, y_test.shape, x_train.shape, y_train.shape

((2138, 14), (2138,), (4276, 14), (4276,))

In [20]:
from imblearn.over_sampling import RandomOverSampler

os = RandomOverSampler(random_state = 42, sampling_strategy='auto')


x_test_res, y_test_res = os.fit_resample(x_test, y_test)

In [21]:
from collections import Counter

print("Original dataset shape {}".format(Counter(y)))

print("Resampled dataset shape {}".format(Counter(y_test_res)))

Original dataset shape Counter({'Moderate': 2138, 'Unhealthy': 253, 'Healthy': 105})
Resampled dataset shape Counter({'Healthy': 713, 'Moderate': 713, 'Unhealthy': 713})

In [ ]:

#from sklearn.model_selection import train_test_split;

#x_train_1, x_test_1, y_train_2, y_test_2 = train_test_split(x_test_res, y_test_res, test_size = 1/3, random_state = 6, stratify = y_train_res);

In [ ]:
#x_test_res.shape, y_test_res.shape

In [22]:
from sklearn.preprocessing import StandardScaler;

standardization = StandardScaler();

x_train = standardization.fit_transform(x_train);

x_test = standardization.transform(x_test);

In [23]:
from sklearn.ensemble import RandomForestClassifier;

from sklearn.model_selection import GridSearchCV;

param_grid = {'criterion':['gini','entropy'],
              'max_features': ['auto','sqrt'], "bootstrap" : [True, False],
              'n_estimators':[10, 20, 50, 80, 100], 
               "max_samples":[1.0]} 

grid = GridSearchCV(RandomForestClassifier(), param_grid, refit = True, verbose = 3, n_jobs=-1, scoring='f1') 


grid.fit(x_train, y_train);

Fitting 5 folds for each of 40 candidates, totalling 200 fits

C:\Users\hp\Anaconda3\envs\virtualml\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning:
100 fits failed out of a total of 200.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
100 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\hp\Anaconda3\envs\virtualml\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\hp\Anaconda3\envs\virtualml\lib\site-packages\sklearn\ensemble\_forest.py", line 380, in fit
    "`max_sample` cannot be set if `bootstrap=False`. "
ValueError: `max_sample` cannot be set if `bootstrap=False`. Either switch to `bootstrap=True` or set `max_sample=None`.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\hp\Anaconda3\envs\virtualml\lib\site-packages\sklearn\model_selection\_search.py:972: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan]
  category=UserWarning,

In [24]:
y_pred = grid.predict(x_test);

In [25]:
from sklearn.metrics import confusion_matrix;

logisticRegressionConfusionMatrix = confusion_matrix(y_test, y_pred);

print(logisticRegressionConfusionMatrix);

[[712   0   0]
 [ 11 699   3]
 [  0   0 713]]

In [26]:
from sklearn.metrics import classification_report;

logisticRegressionClassifierReport = classification_report(y_test, y_pred);

print(logisticRegressionClassifierReport);

              precision    recall  f1-score   support

     Healthy       0.98      1.00      0.99       712
    Moderate       1.00      0.98      0.99       713
   Unhealthy       1.00      1.00      1.00       713

    accuracy                           0.99      2138
   macro avg       0.99      0.99      0.99      2138
weighted avg       0.99      0.99      0.99      2138

In [27]:
from sklearn.metrics import accuracy_score;

SVMClassifierAccuracy = accuracy_score(y_test, y_pred);

print(SVMClassifierAccuracy);

0.9934518241347053

In [28]:
from sklearn.metrics import balanced_accuracy_score;

SVMClassifierBalanced = balanced_accuracy_score(y_test, y_pred);

print(SVMClassifierBalanced);

0.9934548854604955